### ISSUE TITLE
obs信息内容疑问

### ISSUE THREAD

**Issue by lenLRX** [jidiai/Competition_Olympics-Integrated#2]
obs信息只包括(40, 40)的2D数组吗？
关于当前环境信息可以从什么方式获得呢？比如获取当前是足球还是相扑？

**Comment by zhanghongjie101** [comment]
我觉得吧，就是不让你知道，知道的话，直接每个任务一个policy就可以了。不过你可以学一个模型先来判断是哪个任务，但这样就没体现出policy的泛化性了，多智能体多任务泛化性应该是比赛的目的。个人想法，仅供参考。

**Comment by zhanghongjie101** [comment]
> obs信息只包括(40, 40)的2D数组吗？ 关于当前环境信息可以从什么方式获得呢？比如获取当前是足球还是相扑？

我觉得吧，就是不让你知道，知道的话，直接每个任务一个policy就可以了。不过你可以学一个模型先来判断是哪个任务，但这样就没体现出policy的泛化性了，多智能体多任务泛化性应该是比赛的目的。个人想法，仅供参考。

**Comment by ZF4444** [comment]
请问你解决了这个问题吗？这个比赛关于环境的介绍比较少

**Comment by smoothsmooth** [comment]
这个环境通过观测获取不到是哪个子游戏，通过'obs'里的‘game_mode’能看出是否有新的子游戏开始运行（值为'NEW GAME'），通过'obs'中的'id'判断是哪一方，'obs'中的‘energy’表示能量。可以把all_observes打出来看一下。
